module.exports = {
  apps: [
    {
      name: 'ornina-frontend',
      script: 'npm',
      args: 'start',
      cwd: '/var/www/avatar/frontend',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
      },
      error_file: '/var/log/ornina-frontend-error.log',
      out_file: '/var/log/ornina-frontend-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '500M',
    },
    {
      name: 'ornina-backend',
      script: 'agent.py',
      args: 'dev',
      cwd: '/var/www/avatar/avatary',
      instances: 1,
      exec_mode: 'fork',
      interpreter: '/var/www/avatar/avatary/venv/bin/python3',
      env: {
        PATH: '/var/www/avatar/avatary/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
        VIRTUAL_ENV: '/var/www/avatar/avatary/venv',
        PYTHONUNBUFFERED: '1',
      },
      error_file: '/var/log/ornina-backend-error.log',
      out_file: '/var/log/ornina-backend-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '1G',
    },
  ],
};
